
from enum import Enum


class MissionState(Enum):
    EXTRACTED = "EXTRACTED"
    EXTRACTING = "EXTRACTING"
    MOVING_TO_EXTRACTION = "MOVING_TO_EXTRACTION"
    COMPLETED = "COMPLETED"
    IN_PROGRESS = "IN_PROGRESS"
    STARTING = "STARTING"
    MOVING_TO_DROP_POINT = "MOVING_TO_DROP_POINT"
    FINDING_MATCH = "FINDING_MATCH"
    JOINING_MATCH = "JOINING_MATCH"
