
from enum import Enum


class SectorState(Enum):
    LIBERATED = "LIBERATED"
    CAPTURED = "CAPTURED"
    UNDER_REINFORCEMENT = "UNDER_REINFORCEMENT"
    WAITING_FOR_INTEL = "WAITING_FOR_INTEL"
    PARTIALLY_REINFORCED = "PARTIALLY_REINFORCED"


class SectorHotSpotState(Enum):
    IDLE = "IDLE"
    CONGESTED_CONTROL = "CONGESTED_CONTROL"
    SECURE = "SECURE"